"""Compatibility facade for config-store implementation internals."""

from core.config_store_support.impl import (
    AppConfig,
    AppSettings,
    DEFAULT_CONFIG,
    WindowGeometry,
    _coerce_auto_backup_minutes_for_import,
    _coerce_bool_for_import,
    _coerce_int_range_for_import,
    _canonical_query_key,
    _dpapi_decrypt_text,
    _dpapi_encrypt_text,
    _is_windows_platform,
    _normalize_alert_keywords,
    _normalize_auto_backup_minutes,
    _normalize_cloud_sync_interval_minutes,
    _normalize_saved_search_dates,
    _normalize_secret_storage,
    _to_bool,
    _to_int,
    _to_keyword_groups,
    _to_pagination_state,
    _to_pagination_totals,
    _to_saved_searches,
    _to_str_list,
    _to_tab_refresh_policies,
    _valid_date_string,
    _write_text_atomic,
    default_config,
    encode_client_secret_for_storage,
    load_config_file,
    normalize_import_settings,
    normalize_loaded_config,
    resolve_client_secret_for_runtime,
    save_config_file_atomic,
    save_primary_config_file,
)
from core.config_store_support.impl import *  # noqa: F401,F403
